//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Login
{
    using System;
    using System.Collections.Generic;
    
    public partial class pembayaran
    {
        public int Id { get; set; }
        public string nama { get; set; }
        public string order { get; set; }
        public int no_pemesanan { get; set; }
    }
}
