//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Login
{
    using System;
    using System.Collections.Generic;
    
    public partial class pemesanan
    {
        public int Id { get; set; }
        public string nama_menu { get; set; }
        public int harga { get; set; }
        public int total_harga { get; set; }
        public int jumlah { get; set; }
    }
}
